FROM node:20-alpine AS builder
WORKDIR /app
COPY apps/web/package.json /app/
RUN npm install
COPY apps/web /app/
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 3000
CMD ["npm", "start"]
